services:
  api:
    container_name: nestjs_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: ["npm", "run", "start:dev"]

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=erpuser
      - POSTGRES_PASSWORD=erppassword
      - POSTGRES_DB=erp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U erpuser -d erp_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 