name: Update SDK

on:
  push:
    branches:
      - main
    paths:
      - 'swagger.json'
      - 'src/**/*.ts'
  workflow_dispatch:

jobs:
  check-breaking-changes:
    runs-on: ubuntu-latest
    outputs:
      has_breaking: ${{ steps.check-breaking.outputs.has_breaking }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Check for breaking changes
        id: check-breaking
        run: |
          CHANGES=$(npm run check:breaking-changes)
          echo "has_breaking=$(echo $CHANGES | grep -c "BREAKING" || true)" >> $GITHUB_OUTPUT
          echo "$CHANGES" > breaking-changes.txt

      - name: Create Issue for Breaking Changes
        if: steps.check-breaking.outputs.has_breaking != '0'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const changes = fs.readFileSync('breaking-changes.txt', 'utf8');
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '⚠️ Breaking Changes Detected in API',
              body: `Breaking changes detected in the API:\n\n\`\`\`\n${changes}\n\`\`\`\n\nPlease review and update the major version number if proceeding with these changes.`,
              labels: ['breaking-change']
            });

  update-sdk:
    needs: check-breaking-changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SDK_DEPLOY_KEY }}

      - name: Generate and update SDK
        run: |
          # Generate the SDK
          npm run generate:sdk
          
          # Debug: Check what was generated
          echo "Contents of tmp-sdk directory:"
          ls -la tmp-sdk
          
          # Clone SDK repo
          git clone git@github.com:plugnio/BAWES-ERP-sdk.git sdk-repo
          cd sdk-repo
          git checkout main
          
          # Copy new SDK files from tmp-sdk to sdk-repo
          echo "Copying new SDK files..."
          cp -rv ../tmp-sdk/* .
          
          echo "Contents of sdk-repo after copy:"
          ls -la
          
          # Build the SDK
          npm run build
          
          echo "Git status before add:"
          git status
          
          # Stage all changes
          git add -A
          
          echo "Git status after add:"
          git status
          
          # Check if there are any changes after staging
          if git diff --staged --quiet; then
            echo "No changes detected in the SDK files. Skipping version bump and publish."
            exit 0
          else
            echo "Changes detected in SDK files"
            # Changes exist, proceed with version bump and publish
            if [ "${{ needs.check-breaking-changes.outputs.has_breaking }}" != "0" ]; then
              npm version major
            else
              npm version minor
            fi
            
            # Update CHANGELOG.md
            echo "## [$(npm pkg get version | tr -d '"')] - $(date +'%Y-%m-%d')" >> CHANGELOG.md
            echo "" >> CHANGELOG.md
            if [ "${{ needs.check-breaking-changes.outputs.has_breaking }}" != "0" ]; then
              echo "### Breaking Changes" >> CHANGELOG.md
              cat ../breaking-changes.txt >> CHANGELOG.md
            else
              echo "### Changes" >> CHANGELOG.md
              echo "- Updated SDK based on latest API changes" >> CHANGELOG.md
            fi
            echo "" >> CHANGELOG.md
            cat CHANGELOG.md.tmp >> CHANGELOG.md
            
            # Commit and push changes
            git add .
            git commit -m "chore: update SDK to version $(npm pkg get version | tr -d '"')"
            git push --follow-tags
            
            # Publish to GitHub Packages
            npm publish
          fi
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}